name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context (current directory)
          file: ./Dockerfile  # Path to your Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # Specify the target platforms you want to support
          push: true
          tags: |
            yourusername/yourimage:latest
            yourusername/yourimage:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
